import { Category, Product, StoreSettings, User, DeliveryZone } from './types';
import bcrypt from 'bcryptjs';

// Pre-hashed default password: "Password@123"
// Generated with bcrypt.hashSync('Password@123', 10)
const DEFAULT_HASH = bcrypt.hashSync('Password@123', 10);

export const SEED_USERS: User[] = [
  {
    id: 'usr_owner_1',
    name: 'Jay Diamond (Proprietor)',
    email: 'owner@diamondjay.com',
    phone: '+233 248 565 916',
    passwordHash: DEFAULT_HASH,
    role: 'owner',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr_staff_1',
    name: 'Kwame Mensah',
    email: 'staff@diamondjay.com',
    phone: '+233241000002',
    passwordHash: DEFAULT_HASH,
    role: 'staff',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'usr_customer_1',
    name: 'Akosua Serwaa',
    email: 'customer@diamondjay.com',
    phone: '+233241000003',
    passwordHash: DEFAULT_HASH,
    role: 'customer',
    createdAt: new Date().toISOString(),
  },
];

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat_whisky_spirits',
    name: 'Whisky & Spirits',
    slug: 'whisky-spirits',
    description: 'Single malts, blended scotch, bourbon, gin, rum, and vodka.',
    image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat_wines',
    name: 'Fine Wines',
    slug: 'wines',
    description: 'Curated red, white, rosé, and sweet dessert wines from top vineyards.',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat_champagne',
    name: 'Champagnes & Sparkling',
    slug: 'champagnes',
    description: 'Prestige champagnes, prosecco, and sparkling celebration wines.',
    image: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat_beer_cider',
    name: 'Beers & Ciders',
    slug: 'beers-ciders',
    description: 'Chilled local Ghanaian brews, international draughts, stouts, and ciders.',
    image: 'https://images.unsplash.com/photo-1608270199042-45e0f73fce81?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat_liqueurs_bitters',
    name: 'Liqueurs & Local Bitters',
    slug: 'liqueurs-bitters',
    description: 'Cream liqueurs, herbal aperitifs, and renowned authentic Ghanaian bitters.',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'cat_soft_drinks',
    name: 'Mixers & Soft Drinks',
    slug: 'mixers-soft-drinks',
    description: 'Tonic waters, sodas, energy drinks, mineral water, and premium cocktail mixers.',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80',
  },
];

export const SEED_PRODUCTS: Product[] = [
  // Whisky & Spirits
  {
    id: 'prod_jw_black',
    name: 'Johnnie Walker Black Label 12 Year Old',
    category: 'whisky-spirits',
    price: 450,
    stockQuantity: 28,
    volume: '750ml',
    alcoholPercentage: 40.0,
    originCountry: 'Scotland',
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=800&q=80',
    description: 'An iconic blend of up to 40 whiskies aged for at least 12 years. Rich, complex, and incredibly well-balanced with dark fruit, sweet vanilla, and signature smokiness.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_jameson',
    name: 'Jameson Irish Whiskey',
    category: 'whisky-spirits',
    price: 360,
    stockQuantity: 45,
    volume: '750ml',
    alcoholPercentage: 40.0,
    originCountry: 'Ireland',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&q=80',
    description: 'Triple-distilled Irish whiskey that is as smooth as it is versatile. Perfect neat, on the rocks, or mixed with ginger ale and lime.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_hennessy_vs',
    name: 'Hennessy Very Special (VS) Cognac',
    category: 'whisky-spirits',
    price: 680,
    stockQuantity: 20,
    volume: '750ml',
    alcoholPercentage: 40.0,
    originCountry: 'France',
    imageUrl: 'https://images.unsplash.com/photo-1582819509241-913417cba4b4?auto=format&fit=crop&w=800&q=80',
    description: 'A timeless benchmark in cognac. Vibrant and full-bodied with notes of toasted oak, fresh grapes, and roasted almonds.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_tanqueray',
    name: 'Tanqueray London Dry Gin',
    category: 'whisky-spirits',
    price: 320,
    stockQuantity: 34,
    volume: '750ml',
    alcoholPercentage: 43.1,
    originCountry: 'United Kingdom',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    description: 'Crafted from the finest botanicals with prominent juniper, coriander, angelica, and liquorice. The gold standard for a refreshing Gin & Tonic.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_absolut_vodka',
    name: 'Absolut Original Swedish Vodka',
    category: 'whisky-spirits',
    price: 260,
    stockQuantity: 50,
    volume: '1L',
    alcoholPercentage: 40.0,
    originCountry: 'Sweden',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    description: 'Distilled from winter wheat in Sweden with zero added sugar. Clean, pure, and rich, full of character and smooth on the finish.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Fine Wines
  {
    id: 'prod_casillero_cabernet',
    name: 'Casillero del Diablo Cabernet Sauvignon',
    category: 'wines',
    price: 165,
    stockQuantity: 60,
    volume: '750ml',
    alcoholPercentage: 13.5,
    originCountry: 'Chile',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    description: 'Chilean classic deep ruby red wine. Intense aromas of cherries, black plums, and toasted oak with velvety tannins and good persistence.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_don_simon_sangria',
    name: 'Don Simon Spanish Sangria',
    category: 'wines',
    price: 65,
    stockQuantity: 75,
    volume: '1.5L',
    alcoholPercentage: 7.0,
    originCountry: 'Spain',
    imageUrl: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?auto=format&fit=crop&w=800&q=80',
    description: 'Crisp, fruity, and delightfully sweet Spanish sangria infused with Mediterranean citrus and cinnamon spices. Best served chilled over ice with fresh citrus slices.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_whispering_angel',
    name: 'Whispering Angel Côtes de Provence Rosé',
    category: 'wines',
    price: 380,
    stockQuantity: 18,
    volume: '750ml',
    alcoholPercentage: 13.0,
    originCountry: 'France',
    imageUrl: 'https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?auto=format&fit=crop&w=800&q=80',
    description: 'The worldwide benchmark for Provence rosé. Elegant pale salmon hue with subtle peach, melon, and floral notes, crisp acidity and silky finish.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Champagnes & Sparkling
  {
    id: 'prod_moet_imperial',
    name: 'Moët & Chandon Brut Impérial Champagne',
    category: 'champagnes',
    price: 1250,
    stockQuantity: 14,
    volume: '750ml',
    alcoholPercentage: 12.0,
    originCountry: 'France',
    imageUrl: 'https://images.unsplash.com/photo-1569919659476-f0852f6834b7?auto=format&fit=crop&w=800&q=80',
    description: 'The house’s iconic champagne. Distinguished by bright fruitiness, a seductive palate, and an elegant maturity with lively white peach, pear, and brioche nuances.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_veuve_clicquot',
    name: 'Veuve Clicquot Yellow Label Brut',
    category: 'champagnes',
    price: 1350,
    stockQuantity: 12,
    volume: '750ml',
    alcoholPercentage: 12.0,
    originCountry: 'France',
    imageUrl: 'https://images.unsplash.com/photo-1594911772125-07fc7a2d8d9f?auto=format&fit=crop&w=800&q=80',
    description: 'Famous for its powerful pinot noir dominance, freshness, and vanilla richness. Perfect for luxury celebrations and prestigious gifting.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Beers & Ciders
  {
    id: 'prod_club_bottle',
    name: 'Club Premium Lager Beer (Single Bottle)',
    category: 'beers-ciders',
    price: 18,
    stockQuantity: 150,
    volume: '625ml',
    alcoholPercentage: 5.0,
    originCountry: 'Ghana',
    imageUrl: 'https://images.unsplash.com/photo-1608270199042-45e0f73fce81?auto=format&fit=crop&w=800&q=80',
    description: 'Ghana’s pride and joy! Brewed with finest hops and golden malted barley. Truly refreshing taste, perfectly suited for the Accra climate.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_club_crate',
    name: 'Club Premium Lager (Full Crate — 12 Large Bottles)',
    category: 'beers-ciders',
    price: 210,
    stockQuantity: 40,
    volume: '12 x 625ml',
    alcoholPercentage: 5.0,
    originCountry: 'Ghana',
    imageUrl: 'https://images.unsplash.com/photo-1538488881523-298a007c0330?auto=format&fit=crop&w=800&q=80',
    description: 'Special wholesale pack for parties, events, and family gatherings. Includes 12 large chilled bottles of Club Beer.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_guinness_extra',
    name: 'Guinness Foreign Extra Stout',
    category: 'beers-ciders',
    price: 22,
    stockQuantity: 110,
    volume: '330ml',
    alcoholPercentage: 7.5,
    originCountry: 'Ghana / Ireland',
    imageUrl: 'https://images.unsplash.com/photo-1584225064785-c62a8b43d148?auto=format&fit=crop&w=800&q=80',
    description: 'Rich, dark, and deeply rewarding with a bitter-sweet character and intense roasted coffee and chocolate notes.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_heineken',
    name: 'Heineken Premium Lager Can (Pack of 6)',
    category: 'beers-ciders',
    price: 85,
    stockQuantity: 65,
    volume: '6 x 330ml',
    alcoholPercentage: 5.0,
    originCountry: 'Netherlands',
    imageUrl: 'https://images.unsplash.com/photo-1618886614638-80e3c15cd819?auto=format&fit=crop&w=800&q=80',
    description: 'Crisp, clean taste with a subtly bitter finish. Six 330ml cans convenient for chilling and on-the-go enjoyment.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_savanna_dry',
    name: 'Savanna Dry Premium Cider (Pack of 6)',
    category: 'beers-ciders',
    price: 115,
    stockQuantity: 38,
    volume: '6 x 330ml',
    alcoholPercentage: 5.5,
    originCountry: 'South Africa',
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?auto=format&fit=crop&w=800&q=80',
    description: 'Crisp, dry South African apple cider. Best served ice cold with a slice of lemon in the neck.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Liqueurs & Bitters
  {
    id: 'prod_alomo_bitters',
    name: 'Alomo Bitters Herbal Alcoholic Drink',
    category: 'liqueurs-bitters',
    price: 45,
    stockQuantity: 90,
    volume: '750ml',
    alcoholPercentage: 42.0,
    originCountry: 'Ghana',
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80',
    description: 'Ghana’s world-acclaimed traditional herbal formulation made with carefully selected therapeutic plant extracts and roots.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_baileys',
    name: 'Baileys Original Irish Cream',
    category: 'liqueurs-bitters',
    price: 290,
    stockQuantity: 30,
    volume: '750ml',
    alcoholPercentage: 17.0,
    originCountry: 'Ireland',
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=800&q=80',
    description: 'The luscious marriage of real Irish dairy cream, rich cocoa, smooth vanilla, and triple-distilled Irish whiskey.',
    isFeatured: true,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_jagermeister',
    name: 'Jägermeister Herbal Liqueur',
    category: 'liqueurs-bitters',
    price: 310,
    stockQuantity: 25,
    volume: '700ml',
    alcoholPercentage: 35.0,
    originCountry: 'Germany',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=800&q=80',
    description: 'Mastercrafted German herbal liqueur made with 56 natural herbs, blossoms, roots, and fruits. Best served ice-cold as a shot.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },

  // Mixers & Soft Drinks
  {
    id: 'prod_schweppes_tonic',
    name: 'Schweppes Indian Tonic Water (Pack of 6)',
    category: 'mixers-soft-drinks',
    price: 60,
    stockQuantity: 80,
    volume: '6 x 330ml',
    alcoholPercentage: 0.0,
    originCountry: 'Ghana',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    description: 'Classic effervescent tonic with pleasant bitter quinine notes. Essential mixer for dry gins and premium vodkas.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_coca_cola',
    name: 'Coca-Cola Original Taste (Pack of 6 Cans)',
    category: 'mixers-soft-drinks',
    price: 45,
    stockQuantity: 120,
    volume: '6 x 330ml',
    alcoholPercentage: 0.0,
    originCountry: 'Ghana',
    imageUrl: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=800&q=80',
    description: 'Chilled six-pack cans of original Coca-Cola. Perfect standalone refreshment or as a mixer for whiskey and dark rum.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_red_bull',
    name: 'Red Bull Energy Drink (Pack of 4)',
    category: 'mixers-soft-drinks',
    price: 90,
    stockQuantity: 55,
    volume: '4 x 250ml',
    alcoholPercentage: 0.0,
    originCountry: 'Austria',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    description: 'Vitalizes body and mind with caffeine, taurine, B-group vitamins, and sugars. Popular party mixer for night gatherings.',
    isFeatured: false,
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const SEED_DELIVERY_ZONES: DeliveryZone[] = [];

export const SEED_STORE_SETTINGS: StoreSettings = {
  storeName: 'Diamond Jay Enterprise',
  tagline: 'Premium Wines, Spirits, Beers & Liquors in Accra',
  address: '410 New Road',
  city: 'Accra',
  country: 'Ghana',
  phone: '+233 248 565 916',
  whatsapp: '+233 248 565 916',
  email: 'diamondjayenterprise24@gmail.com',
  minOrderAge: 18,
  businessHours: [
    { day: 'Monday - Thursday', open: '07:00 AM', close: '09:00 PM' },
    { day: 'Friday - Saturday', open: '07:00 AM', close: '09:00 PM' },
    { day: 'Sunday', open: '07:00 AM', close: '09:00 PM' },
  ],
  deliveryZones: SEED_DELIVERY_ZONES,
  announcementBanner: {
    enabled: true,
    text: '🎉 Welcome to Diamond Jay Enterprise! Fast delivery across Accra & free in-store pickup at 410 New Road.',
  },
  paystackPublicKey: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY || 'pk_test_placeholder_diamondjay',
};
